### ISSUE TITLE
Readme translations

### ISSUE THREAD

**Issue by s-kostyuk** [fritzing/eagle2fritzing#11]
eagle2fritzing tools are quite complex. So, to understand their work by myself and help to understand work of tools to other users, I started a README files translation into Russian in a new branch: [translated_readme](https://github.com/s-kostyuk/eagle2fritzing/tree/translated_readme). Pull request will be sent as soon as translation will be finished.

Progress (Russian translation):
- [X] translate root readme file
- [X] translate brd2svg readme
  - [X] 1/3 translated
  - [X] 2/3 translated
  - [X] fully translated
- [ ] translate lbr2svg readme

**Comment by aknoerig** [comment]
Great, good idea. :) It would also be nice to add a minimal example: command line calls together with a sample brd and params. This way it will be much easier for people to get started.

**Comment by s-kostyuk** [comment]
I'll try to add examples after finishing of a translation.

I have a question about "description files". How to write them, what they exactly contain? Can you explain it and provide some example? As an example I mean a zip-archive which contain the whole working folder with source (.brd), config (.params, desctription files and so on with maximum of information in each file) and result (.fzp, .svg) files in it. This will be great for further translation and improving of a readme.

**Comment by aknoerig** [comment]
The description file should contain the textual description of the part, so a free-form, human-readable text. It appears when hovering over the part in the parts bin, see this example:
![bildschirmfoto 2015-08-15 um 15 45 57](https://cloud.githubusercontent.com/assets/481350/9289096/c59c25a8-4364-11e5-8710-03f0425f95e4.png)

For the example, maybe simply create a subfolder "example" that contains all the necessary files, and a readme that outlines all the steps. This way we can easily update it through git.
Thanks!

**Comment by s-kostyuk** [comment]
"For the example, maybe simply create a subfolder "example" that contains all the necessary files, and a readme that outlines all the steps. This way we can easily update it through git." - This will be great, really.

Thank you for explanation :)

**Comment by s-kostyuk** [comment]
What about URL in metadata.dif? Please, show example feed URL and outline the text block which be extracted and saved as a part description for some random part. I want to understand what exactly brd2svg is looking for and why RSS was used for an extraction of a part description?

**Comment by aknoerig** [comment]
First of all, every part's metadata contains an optional URL that should point to the part's online documentation.

The script additionally tries to automatically extract a description text from that URL by appending a '.json'. This should work at least with the SparkFun website, e.g. https://www.sparkfun.com/products/13339 and https://www.sparkfun.com/products/13339.json

**Comment by s-kostyuk** [comment]
Understood. Thank you

**Comment by s-kostyuk** [comment]
Closed. Until someone will need this translation
