### ISSUE TITLE
OS X version

### ISSUE THREAD

**Issue by emnullfuenf** [fritzing/eagle2fritzing#13]
Is there a way to build an OS X command line version?

**Comment by s-kostyuk** [comment]
brd2svg and lbr2svg are both command-line tools, actually. And the most simple way to build them - build via Qt Creator (which can be found in Qt bundle here: http://www.qt.io/download/). Also, you can use qmake to generate makefiles and then build this tools with your favorite C++ compiler. Or anything else I was forgot or don't know about. For more details, maybe it's better to wait for a comment from the project maintainers.

**Comment by s-kostyuk** [comment]
Also this readme may help: https://github.com/fritzing/eagle2fritzing/tree/master/brd2svg, "How to build" section

**Comment by emnullfuenf** [comment]
Thanks. Build it on OS X.

Folder structure:
some_folder
|-- eagle2fritzing
|-- fritzing-app

Installed qt via brew:
brew install qt

Created the make file:
qmake -spec macx-g++ brd2svg.pro

Executed brd2svg:
./brd2svg
