### ISSUE TITLE
Crashes at LbrApplication::getBounds the QTransform says it is not an instance of QguiApplication

### ISSUE THREAD

**Issue by magpern** [fritzing/eagle2fritzing#14]
I have tried and compile this for hours, but always got an exception saying it is not a QGUIApplication. It always crached at line 2275 in LbrApplication::getBounds.
Changing it to a QGuiApplication solved the problem and made application runnable.

I have proposed a fix, but I have never worked with GitHub and don't know what to do next

**Comment by aknoerig** [comment]
Thanks -- however I can't find a mention of QGUIApplication anywhere. There are two places where it already says QGuiApplication: https://github.com/fritzing/eagle2fritzing/search?utf8=%E2%9C%93&q=qgui
Can you point to the line where you had to change it?

**Comment by magpern** [comment]
I did the fix in i fork, but my knowledge of GitHub is zero. I pressed the Create Pull request now, maybe you can see it now?
I changed the definition of LbrApplication to QGuiApplication (lbrapplication.h)
#include QGuiApplication
class LbrApplication : public QGuiApplication

And the entrypoint in lbrapplication.cpp to 
LbrApplication::LbrApplication(int &argc, char **argv[]) : QGuiApplication(argc, *argv)

(don't know if the latter is needed). I am a .NET developer, and c++ is not my strong side.

**Comment by aknoerig** [comment]
Thanks, this is the correct fix. QGuiApplication (or QApplication) is required to process fonts, that's why it crashed at calculating font metrics.
