### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by s-kostyuk** [fritzing/eagle2fritzing#2]
Maybe this is obvious, but isn't mentioned in readme files. There is unable to build brd2svg and lbr2svg without Fritzing sources. And more, folder with Fritzing sources must be strictly named `fritzing-app` and be placed in the same folder with `eagle2fritzing`

So, folder structure to build tools from this repo:

```
some_folder
|-- eagle2fritzing
|-- fritzing-app
```

Please, add this information to readme file. And sorry for my English

**Comment by aknoerig** [comment]
Thanks, good point!
