### ISSUE TITLE
unable to parse board xml

### ISSUE THREAD

**Issue by jadeye** [fritzing/eagle2fritzing#21]
Hello
Thanx for sharing this...
I am running into an error:
```
$ ./brd2svg -w ./atWork/ -e /opt/eagle/
looking for all.packages.txt in "/opt/eagle2fritzing/brd2svg/all.packages.txt" 
"unable to start Adafruit_Feather_Zero_BLE_rev_A.brd" 
"unable to parse board xml 'Adafruit_Feather_Zero_BLE_rev_A.xml': unexpected end of file line:1 col:1" 
generating bin 
done 
```
IO tried running it on my home folder (permissions on opt folder??) but in vain...
Looked the issue up and found [this_adafruit_forum_post](https://forums.adafruit.com/viewtopic.php?f=8&t=118479&p=612809#p612809)
I am following every instruction but still it fails...
Any ideas?
I am on ubuntu 14.04
Thanx

**Comment by jadeye** [comment]
Tried with another .brd file, same:

```
/eagle2fritzing/brd2svg$ ./brd2svg -w ./work/ -e /opt/eagle/
looking for all.packages.txt in "/home/ubuntu/Documents/BT_SB/pcb/eagle2fritzing/brd2svg/all.packages.txt" 
"unable to start LSM6DS3_Breakout_Panel_v10.brd" 
"unable to parse board xml 'LSM6DS3_Breakout_Panel_v10.xml': unexpected end of file line:1 col:1" 
generating bin 
done
```

**Comment by s-kostyuk** [comment]
Try to use this fork: https://github.com/adafruit/eagle2fritzing/

**Comment by jadeye** [comment]
Thanx...
Sort of an issue as well....
```
$ ./run.sh 
Traceback (most recent call last):
  File "preprocess.py", line 37, in <module>
    dom = parse(sys.argv[1])    # infile
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 2] No such file or directory: '/home/jadeye/Desktop/FritzingTest/brds/*.brd'
./run.sh: line 32: /home/jadeye/Desktop/FritzingTest/brds/*.brd: No such file or directory
./run.sh: line 33: /home/jadeye/Desktop/FritzingTest/brds/*.brd.tmp: No such file or directory
cp: cannot stat ‘/home/jadeye/Desktop/FritzingTest/brds/*.brd’: No such file or directory
mv: cannot stat ‘/home/jadeye/Desktop/FritzingTest/brds/*.brd.tmp’: No such file or directory
eagle executable '/Applications/EAGLE-7.3.0/EAGLE.app/Contents/MacOS/EAGLE' not found
usage: brd2svg -w <path to working folder (containing brds folder)> -e <path to eagle executable> -c <core or contrib> -g (set only for generic smd ic generation) -s <path to subparts folder> -p <path to second subparts folder> -a <path to 'and' folder> 
cp: cannot stat ‘/home/jadeye/Desktop/FritzingTest/parts’: No such file or directory
jadeye@jadeye-desktop:/opt/eagle2fritzing/brd2svg$ ./brd2svg -w /opt/eagle2fritzing/brd2svg/work -e /opt/eagle
looking for all.packages.txt in "/opt/eagle2fritzing/brd2svg/all.packages.txt" 
"unable to start LSM6DS3_Breakout_Panel_v10.brd" 
"unable to start SparkFun-LSM9DS1-Breakout.brd" 
unable to parse board xml 'LSM6DS3_Breakout_Panel_v10.xml': unexpected end of file line:1 col:1 unable to parse board xml 'SparkFun-LSM9DS1-Breakout.xml': unexpected end of file line:1 col:1
generating bin 
done
```
Any ideas??

**Comment by s-kostyuk** [comment]
Looks like it failed on stage 'run .ulp file in Eagle'. To fix that, modify original `run.sh` file:
- on line 4 of `run.sh` file set an `EXEC` variable value to the **full** path to Eagle executable **file**; for example for my computer this line will look like this: `EXEC=/home/srgk/.local_apps/eagle/bin/eagle`;
- on line 14 of `run.sh` you may want to change a value of `TESTPATH` variable; but keep in mind that the specified directory must exist before `run.sh` script will be ran.

After doing that, I managed to get the following results: https://www.dropbox.com/s/d8vmpqrp9ty3coi/FritzingTest_e2f_issue21.tar.gz?dl=0

**Comment by jadeye** [comment]
Thank you!
Edited the `run.sh` as you mentioned...worx like a charm!
```
$ ./run.sh 
looking for all.packages.txt in "/opt/eagle2fritzing/brd2svg/and/all.packages.txt" 
"wrote LSM6DS3_Breakout_Panel_v10.brd xml" 
"wrote SparkFun-LSM9DS1-Breakout.brd xml" 
parsing "LSM6DS3_Breakout_Panel_v10.xml" 
generating params 
parsing "SparkFun-LSM9DS1-Breakout.xml" 
generating params 
generating bin 
done 
looking for all.packages.txt in "/opt/eagle2fritzing/brd2svg/and/all.packages.txt" 
parsing "LSM6DS3_Breakout_Panel_v10.xml" 
parsing "SparkFun-LSM9DS1-Breakout.xml" 
generating bin 
done
```
Resolved....
Thanx a million...

**Comment by s-kostyuk** [comment]
You are welcome :)

Please, mark this issue as resolved. I'm not a member of this project and I can't change statuses of another's issues. Just a guy who sent several lines of code long time ago

**Comment by el-j** [comment]
thanks for your support and code! 
can you make a pull-request as well. would be nice having the fix in this original repo as well.
thank you in advance

**Comment by s-kostyuk** [comment]
Well, original (this) repository doesn't have a corresponding run.sh script, to which my pull request was originally related. So, to implement similar behavior in the original repository, it's required to make changes in brd2svg source code itself. It can be tricky

**Comment by s-kostyuk** [comment]
@el-j, pull request is ready (for a while): https://github.com/fritzing/eagle2fritzing/pull/22

**Comment by el-j** [comment]
sorry for the delay. thank you. merged now

**Comment by s-kostyuk** [comment]
Glad to see it, thank you :)
