### ISSUE TITLE
lbr2svg doesn't accept any arguments

### ISSUE THREAD

**Issue by s-kostyuk** [fritzing/eagle2fritzing#3]
`lbrapplication.cpp` file on line 2468: there is no elements in `args` list at all. Even argument number 0 (full path to executed binary) isn't present. As a result, lbr2svg is unusable for now. Proof: 
![debug](https://cloud.githubusercontent.com/assets/5122578/9194326/09cce2f2-4023-11e5-9960-d375190a43fc.png)

**Comment by aknoerig** [comment]
Yeah, the tool used to work, but after we upgraded to Qt 5 and moved it to its own repository it got broken. If you can spend some time to make it work again, that would be awesome. It's a very useful little tool that basically lets you import any Eagle lib.

**Comment by s-kostyuk** [comment]
Yes, I know that this tool is great and I need it really :). So, I'll inform if find something

**Comment by s-kostyuk** [comment]
See here: http://stackoverflow.com/questions/12135577/users-arguments-are-empty-with-qcoreapplication-in-mysterious-cases
